# Generated by Django 4.1.2 on 2024-08-27 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_profile_last_name_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
    ]
