# Generated by Django 4.1.2 on 2024-08-27 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_profile_email_alter_profile_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
