# Generated by Django 4.1.2 on 2024-08-29 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
    ]
