# Generated by Django 4.1.2 on 2024-10-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_asignaciontarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='asignada',
            field=models.BooleanField(null=True),
        ),
    ]
