# Generated by Django 4.1.2 on 2024-10-11 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_invitation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='project',
            new_name='proyecto',
        ),
    ]
