# Generated by Django 4.1.2 on 2024-10-11 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_project_invitation_proyecto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='proyecto',
            new_name='proyect',
        ),
    ]
