# Generated by Django 4.1.2 on 2024-10-11 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rename_proyecto_invitation_proyect'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='proyect',
            new_name='project',
        ),
    ]
