# Generated by Django 4.1.2 on 2024-10-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_rename_proyect_invitation_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='fechamax',
            field=models.DateField(null=True),
        ),
    ]
