# Generated by Django 4.1.2 on 2024-10-16 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_proyecto_prioridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='fechaInicio',
            field=models.DateField(null=True),
        ),
    ]
