# Generated by Django 4.1.2 on 2024-10-29 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_tarea_avance_tarea_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cargaTrabajo',
            field=models.IntegerField(null=True),
        ),
    ]
