# Generated by Django 4.1.2 on 2024-10-29 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_profile_cargatrabajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cargaTrabajo',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
