# Generated by Django 5.1.2 on 2024-11-18 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_profile_image_alter_profile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='avance',
            field=models.CharField(choices=[('iniciada', 'Iniciada'), ('cursando', 'Cursando'), ('finalizada', 'Finalizada')], max_length=15, null=True),
        ),
    ]
