# Generated by Django 5.1.2 on 2024-11-25 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_tarea_avance'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reset_password_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
