# Generated by Django 5.1.2 on 2024-12-01 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_task', 'Nueva Tarea'), ('overdue_task', 'Tarea Vencida')], default='', max_length=20),
        ),
    ]
