# Generated by Django 5.1.2 on 2024-12-03 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='avance',
            field=models.CharField(choices=[('iniciada', 'Iniciada'), ('cursando', 'Cursando'), ('finalizada', 'Finalizada')], default='iniciada', max_length=15, null=True),
        ),
    ]
